[package]
name = "github.com/axetroy/watchdog"
bin = "watchdog"
authors = ["Axetroy <axetroy.dev@gmail.com>"]
keywords = []
repository = "https://github.com/axetroy/watchdog"
description = """
çœ‹é—¨ğŸ¶ï¼Œæ‚¨çš„æœåŠ¡çŠ¶æ€ç®¡å®¶ï¼Œæ”¯æŒ TCP/FTP/HTTP/WebSocket/SSH ç­‰åè®®ï¼Œé€šè¿‡Webhook/å¾®ä¿¡/é‚®ä»¶ç­‰å¤šæ¸ é“é€šçŸ¥
"""

[darwin]
x86_64 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_darwin_amd64.tar.gz"
aarch64 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_darwin_arm64.tar.gz"

[windows]
x86 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_windows_386.tar.gz"
x86_64 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_windows_amd64.tar.gz"
aarch64 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_windows_arm64.tar.gz"

[linux]
x86 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_linux_386.tar.gz"
x86_64 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_linux_amd64.tar.gz"
aarch64 = "https://github.com/axetroy/dvm/releases/download/v{version}/watchdog_linux_arm64.tar.gz"